Repository UnionMusic/lianhe.art, pull requests merged in 2021-08, with the labels that each got.

#161 cosm: update description for footer
  src/components/Layout/Footer.tsx
Labels: size/M

#162 cosm: update about page
  src/pages/about.tsx
Labels: size/S

#164 cosm: update the about page
  src/pages/about.tsx
Labels: size/XS

#169 cosm: update introduction
  src/pages/about.tsx
Labels: size/XS

#171 refactor: redirect path for contact centre
  src/pages/contact.tsx
Labels: size/M

#172 feat: products centre
  src/components/Layout/Footer.tsx
  src/pages/products.tsx
Labels: size/M
